### ISSUE TITLE
Chrome won't appear to run passext-host

### ISSUE THREAD

**Issue by sjkingo** [gustaebel/passext#2]
I have followed the instructions in `README` on Google Chrome Beta (linux) but the extension just sits with "Inactive" as its tooltip. `passext-host` never appears to be executed, and no password hinting happens.

I've checked the path to `passext-host` (and am able to execute it manually), and ensured the extension ID is correct.

Any ideas as to where to debug?

**Comment by gustaebel** [comment]
Do you have gnupg version >=2.1 installed?

**Comment by sjkingo** [comment]
Yep, I have version 2.1.4 installed globally (Fedora 22) and `pass` works fine.

**Comment by gustaebel** [comment]
They changed a lot in gnupg2 and this seems to break passext (e.g. it uses its own instance of gpg-agent). I haven't used passext myself for quite a while now, so I didn't realize that it no longer works. But I'm working on it.

**Comment by sjkingo** [comment]
What version did you develop against? I can try that. Strangely it seems like chrome is never executing the `passext-host` script at all (strace not showing it)

**Comment by gustaebel** [comment]
I use chromium 43 for development. For debugging I start it from the command line: `chromium --enable-logging --v=1`, so that I can see `passext-host`'s stderr output.
With gnupg-2.1.6 the current git master version of passext fails with a `"TypeError: %d format: a number is required, not NoneType"`.

**Comment by gustaebel** [comment]
I added support for gpg-2.1. I hope you're more successful now.
